### ISSUE TITLE
Player's interaction reach is smaller than in the original

### ISSUE THREAD

**Issue by Nindaleth** [Try/OpenGothic#290]
It's not an issue most of the time, but then there's moments like when you're in Khorinis and want to talk to Matteo or Bosper - if you stand on the other side of the counter as usual, they aren't highlighted and cannot be talked to.

In the vanilla Gothic, the highlighting starts much sooner - I'm halfway from the door to the counter and they are already highlighted.

**Comment by Try** [comment]
> Matteo or Bosper - if you stand on the other side of the counter as usual, they aren't highlighted and cannot be talked to.

This is from latest stable, right? Yes there was a bug, that is already fixed on `master`

**Comment by Nindaleth** [comment]
> This is from latest stable, right?

Yes, it was convenient for me to just go the [easy way](https://github.com/Try/OpenGothic/issues/281#issuecomment-1216036891) on Steam Deck = using the stable release.

I'll switch to a `master` build to avoid rediscovering issues, thanks for letting me know.

**Comment by Nindaleth** [comment]
`master` build fixes the issue for me, thanks!
Just nitpicking - even after the fix I'm still not able to highlight Bosper's signboard above the entrance.

**Comment by Try** [comment]
Oh, wait a momoent:
```c++
void Gothic::ai_printscreen(Daedalus::DaedalusVM& vm) {
  // TODO: print-screen queue
  ...
```
Sorry, I forgot to implement it ;D

**Comment by Try** [comment]
> Just nitpicking - even after the fix I'm still not able to highlight Bosper's signboard above the entrance.

This because ray-query fail to reach MOBSI interaction point because signboard geometry block it.

Found one more bug-case on Lobarts farm:
![изображение](https://user-images.githubusercontent.com/122894/213543769-b691ea6f-6223-4ef1-9813-3066a1ec6287.png)

Need to update RQ logic here, probably need to trace to middle of MOBSI

**Comment by Try** [comment]
should be fixed by fa4cdd6f (on a branch at the moment)

**Comment by Try** [comment]
Fixed and merged: https://github.com/Try/OpenGothic/pull/908

**Comment by Nindaleth** [comment]
Thanks!
