### ISSUE TITLE
[G1] Main Menu ok, game start = crash

### ISSUE THREAD

**Issue by dreimer1986** [Try/OpenGothic#455]
I use the German Gothic 1 Version from Steam here. One of the last week commits causes a crash on New Game and Load Game. Main Menu is fine though. It happens just right before going ingame.

Used a MSVC 2022 made 38d1013613bd621a21337f578983910ab68c6319 off my 1:1 branch. Submodules are updated.

Gothic 2 from Steam in German works fine though.

P.S. Yes with the 2080 RTX OpenGothic works, only the AMD causes problems. (https://github.com/Try/OpenGothic/issues/451)

```
---crashlog(ExceptionFilter)---
GPU: NVIDIA GeForce RTX 2080
0x00007ff6746aaa36: dbg::call_stack<64>::collect in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6746aa362: CrashLog::dumpStack in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6746aa51e: exceptionHandler in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ffc5d3ab81c: UnhandledExceptionFilter in C:\WINDOWS\System32\KERNELBASE.dll
0x00007ffc5f8d837d: RtlMoveMemory in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffc5f8befa7: _C_specific_handler in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffc5f8d3cff: _chkstk in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffc5f84e456: RtlFindCharInUnicodeString in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffc5f884455: RtlRaiseException in C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffc5d2b536c: RaiseException in C:\WINDOWS\System32\KERNELBASE.dll
0x00007ffc48a3b760: CxxThrowException in C:\WINDOWS\SYSTEM32\VCRUNTIME140D.dll
0x00007ffbd678f7af: Tempest::Encoder<Tempest::CommandBuffer>::setUniforms in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007ffbd678f6e3: Tempest::Encoder<Tempest::CommandBuffer>::setUniforms in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007ff6745afe0f: Renderer::prepareIrradiance in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6745b11f2: Renderer::draw in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6745ae691: Renderer::draw in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6745f8c99: MainWindow::render in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ffbd67c233e: Tempest::EventDispatcher::dispatchRender in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007ffbd67cb68b: Tempest::SystemApi::dispatchRender in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007ffbd67b7331: Tempest::WindowsApi::implProcessEvents in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007ffbd67b7181: Tempest::WindowsApi::implExec in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007ffbd67cb9c3: Tempest::SystemApi::exec in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007ffbd67bd0c6: Tempest::Application::exec in C:\Users\Daniel\Desktop\opengothic_win\Tempest.dll
0x00007ff6745efd61: main in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6749b08e9: invoke_main in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6749b078e: __scrt_common_main_seh in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6749b064e: __scrt_common_main in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ff6749b097e: mainCRTStartup in C:\Users\Daniel\Desktop\opengothic_win\Gothic2Notr.exe
0x00007ffc5e7f269d: BaseThreadInitThunk in C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffc5f88a9f8: RtlUserThreadStart in C:\WINDOWS\SYSTEM32\ntdll.dll
```

**Comment by Try** [comment]
Hi, @dreimer1986 , thanks for reporting!

> One of the last week commits causes 

Is it possible on your side to bisect and find exact commit? 
Looking at crash: `prepareIrradiance` seem to be problematic, yet this doesn't explain why gothic2 runs fine. Sky irradiance is same for all cases.

**Comment by Try** [comment]
I've merged path related to iradiance today: d0491e11
Since `prepareIrradiance` is offended in crashlog, can you please check if it work on you AMD?

**Comment by thokkat** [comment]
Still crashing, first occurrence: https://github.com/Try/OpenGothic/commit/1e4104ecb4b1c194b1a0be74f022d3b3142dc034

**Comment by Try** [comment]
OK, so you @thokkat  can also reproduce?

On my end so far no luck. Maybe you can check, if commenting call to `prepareIrradiance` helps?

**Comment by thokkat** [comment]
Crash is gone if `prepareIrradiance` is commented out.

**Comment by Try** [comment]
Should be fixed now.

Problem was that for on low-settings uses render-pass, but irradiance didn't switch command buffer to compute mode.
Use to work by accident with HQ for since both effects are compute shaders
