### ISSUE TITLE
Settings UI crashes on ARM

### ISSUE THREAD

**Issue by ak-coram** [Try/OpenGothic#538]
I'm trying to run OpenGothic (current master) with Gothic 2 on my Qualcomm Snapdragon 8cx Gen 3. It runs, but I only get between 10 and 15 FPS with the default settings. Sadly I can't change most of the settings because the application crashes consistently when I try.

This is what I get when trying to adjust the view distance or when trying to open the video settings:
```
$ Gothic2Notr -g ./                                                                                                         
OpenGothic v1.0 dev
no *.ini file in path - using default settings
GPU = Turnip Adreno (TM) 690
Depth format = Depth32F Shadow format = Depth16
/usr/include/c++/12.1.0/string_view:239: constexpr const std::basic_string_view<_CharT, _Traits>::value_type& std::basic_string_view<_CharT, _Traits>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.

---crashlog(SIGABRT)---
GPU: Turnip Adreno (TM) 690
#1:  - /usr/lib/libc.so.6(+0x82790) [0xffffbcab2790]
#2: raise - /usr/lib/libc.so.6(raise+0x2c) [0xffffbca6b6fc]
#3: abort - /usr/lib/libc.so.6(abort+0xe4) [0xffffbca578b0]
#4: abort - /usr/lib/libstdc++.so.6(+0xd2c18) [0xffffbccf2c18]
#5: GameMenu::strEnumSize(std::basic_string_view<char, std::char_traits<char> >) - Gothic2Notr(_ZN8GameMenu11strEnumSizeESt17basic_string_viewIcSt11char_traitsIcEE+0x94) [0xaaaad984e134]
#6: GameMenu::execChgOption(GameMenu::Item&, int) - Gothic2Notr(_ZN8GameMenu13execChgOptionERNS_4ItemEi+0x144) [0xaaaad9853404]
#7: GameMenu::exec(GameMenu::Item&, int) - Gothic2Notr(_ZN8GameMenu4execERNS_4ItemEi+0x70) [0xaaaad9854270]
#8: Tempest::EventDispatcher::implDispatch(Tempest::Widget&, Tempest::MouseEvent&) - Gothic2Notr(_ZN7Tempest15EventDispatcher12implDispatchERNS_6WidgetERNS_10MouseEventE+0x4cc) [0xaaaad99f668c]
#9: Tempest::EventDispatcher::implDispatch(Tempest::Widget&, Tempest::MouseEvent&) - Gothic2Notr(_ZN7Tempest15EventDispatcher12implDispatchERNS_6WidgetERNS_10MouseEventE+0x190) [0xaaaad99f6350]
#10: Tempest::EventDispatcher::dispatchMouseDown(Tempest::Widget&, Tempest::MouseEvent&) - Gothic2Notr(_ZN7Tempest15EventDispatcher17dispatchMouseDownERNS_6WidgetERNS_10MouseEventE+0x464) [0xaaaad99f6c34]
#11: Tempest::X11Api::implProcessEvents(Tempest::SystemApi::AppCallBack&) - Gothic2Notr(_ZN7Tempest6X11Api17implProcessEventsERNS_9SystemApi11AppCallBackE+0x6ec) [0xaaaad99f3b6c]
#12: Tempest::X11Api::implExec(Tempest::SystemApi::AppCallBack&) - Gothic2Notr(_ZN7Tempest6X11Api8implExecERNS_9SystemApi11AppCallBackE+0x44) [0xaaaad99f3c24]
#13: main - Gothic2Notr(main+0x25c) [0xaaaad96add5c]

Aborted (core dumped)
```

**Comment by ak-coram** [comment]
Oh, I forgot to mention I'm running this on an aarch64 Linux distro. Please let me know if you need more details!

**Comment by Try** [comment]
Hi, @ak-coram !
Crash should be fixed now, by [174bcce](https://github.com/Try/OpenGothic/commit/174bcce872ba257714342890ffbcf20052a14e68)

> This is what I get when trying to adjust the view distance

Readme:
```
Available Graphic options
    SSAO (mapped to Cloud Shadows)
    Volumetric fog (mapped to Radial Fog)
    Reflections
    Ray tracing (commandline option, setting affects only capable hardware, off by default for igpu's, add -rt 1 to enable)

Rendering distance is not customizable. <-----
```

**Comment by ak-coram** [comment]
@Try thanks, I can now adjust the view distance. I still get the following when trying to open the "Video" section of the settings:

```
OpenGothic v1.0 dev
no *.ini file in path - using default settings
GPU = Turnip Adreno (TM) 690
Depth format = Depth32F Shadow format = Depth16
/usr/include/c++/12.1.0/string_view:239: constexpr const std::basic_string_view<_CharT, _Traits>::value_type& std::basic_string_view<_CharT, _Traits>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.

---crashlog(SIGABRT)---
GPU: Turnip Adreno (TM) 690
#1:  - /usr/lib/libc.so.6(+0x82790) [0xffff86612790]
#2: raise - /usr/lib/libc.so.6(raise+0x2c) [0xffff865cb6fc]
#3: abort - /usr/lib/libc.so.6(abort+0xe4) [0xffff865b78b0]
#4: abort - /usr/lib/libstdc++.so.6(+0xd2c18) [0xffff86852c18]
#5: GameMenu::strEnum(std::basic_string_view<char, std::char_traits<char> >, int, std::vector<char, std::allocator<char> >&) - Gothic2Notr(_ZN8GameMenu7strEnumESt17basic_string_viewIcSt11char_traitsIcEEiRSt6vectorIcSaIcEE+0xb0) [0xaaaae4367c90]
#6: GameMenu::drawItem(Tempest::Painter&, GameMenu::Item&) - Gothic2Notr(_ZN8GameMenu8drawItemERN7Tempest7PainterERNS_4ItemE+0xb0) [0xaaaae4367fe4]
#7: GameMenu::paintEvent(Tempest::PaintEvent&) - Gothic2Notr(_ZN8GameMenu10paintEventERN7Tempest10PaintEventE+0x15c) [0xaaaae4368d70]
#8: Tempest::Widget::paintNested(Tempest::PaintEvent&) - Gothic2Notr(_ZN7Tempest6Widget11paintNestedERNS_10PaintEventE+0x1ec) [0xaaaae44ce67c]
#9: Tempest::Widget::paintNested(Tempest::PaintEvent&) - Gothic2Notr(_ZN7Tempest6Widget11paintNestedERNS_10PaintEventE+0x188) [0xaaaae44ce618]
#10: Tempest::Window::dispatchPaintEvent(Tempest::VectorImage&, Tempest::TextureAtlas&) - Gothic2Notr(_ZN7Tempest6Window18dispatchPaintEventERNS_11VectorImageERNS_12TextureAtlasE+0x90) [0xaaaae44d0850]
#11: MainWindow::render() - Gothic2Notr(_ZN10MainWindow6renderEv+0x148) [0xaaaae43368e8]
#12: Tempest::X11Api::implProcessEvents(Tempest::SystemApi::AppCallBack&) - Gothic2Notr(_ZN7Tempest6X11Api17implProcessEventsERNS_9SystemApi11AppCallBackE+0x7c) [0xaaaae450d68c]
#13: Tempest::X11Api::implExec(Tempest::SystemApi::AppCallBack&) - Gothic2Notr(_ZN7Tempest6X11Api8implExecERNS_9SystemApi11AppCallBackE+0x44) [0xaaaae450ddb4]
#14: main - Gothic2Notr(main+0x26c) [0xaaaae41c0c5c]

Aborted (core dumped) 
```

**Comment by ak-coram** [comment]
FYI: the game seems perfectly playable on this hardware with the view distances reduced to 100%, I get 30-40 FPS now.

**Comment by ak-coram** [comment]
@Try Thanks for the fixes! Sadly I still get the following when I try to change some of the settings (like combat focus):

```
GPU = Turnip Adreno (TM) 690
Depth format = Depth32F Shadow format = Depth16
/usr/include/c++/12.1.0/string_view:239: constexpr const std::basic_string_view<_CharT, _Traits>::value_type& std::basic_string_view<_CharT, _Traits>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.

---crashlog(SIGABRT)---
GPU: Turnip Adreno (TM) 690
#1:  - /usr/lib/libc.so.6(+0x82790) [0xffff96f12790]
#2: raise - /usr/lib/libc.so.6(raise+0x2c) [0xffff96ecb6fc]
#3: abort - /usr/lib/libc.so.6(abort+0xe4) [0xffff96eb78b0]
#4: abort - /usr/lib/libstdc++.so.6(+0xd2c18) [0xffff97152c18]
#5: GameMenu::strEnumSize(std::basic_string_view<char, std::char_traits<char> >) - Gothic2Notr(_ZN8GameMenu11strEnumSizeESt17basic_string_viewIcSt11char_traitsIcEE+0x94) [0xaaaac73fe134]
#6: GameMenu::execChgOption(GameMenu::Item&, int) - Gothic2Notr(_ZN8GameMenu13execChgOptionERNS_4ItemEi+0x144) [0xaaaac7403404]
#7: GameMenu::exec(GameMenu::Item&, int) - Gothic2Notr(_ZN8GameMenu4execERNS_4ItemEi+0x70) [0xaaaac7404270]
#8: MainWindow::keyUpEvent(Tempest::KeyEvent&) - Gothic2Notr(_ZN10MainWindow10keyUpEventERN7Tempest8KeyEventE+0x1f8) [0xaaaac73cde68]
#9: Tempest::EventDispatcher::dispatchKeyUp(Tempest::Widget&, Tempest::KeyEvent&, unsigned int) - Gothic2Notr(_ZN7Tempest15EventDispatcher13dispatchKeyUpERNS_6WidgetERNS_8KeyEventEj+0x10c) [0xaaaac75a7e00]
#10: Tempest::X11Api::implProcessEvents(Tempest::SystemApi::AppCallBack&) - Gothic2Notr(_ZN7Tempest6X11Api17implProcessEventsERNS_9SystemApi11AppCallBackE+0x4ac) [0xaaaac75a392c]
#11: Tempest::X11Api::implExec(Tempest::SystemApi::AppCallBack&) - Gothic2Notr(_ZN7Tempest6X11Api8implExecERNS_9SystemApi11AppCallBackE+0x44) [0xaaaac75a3c24]
#12: main - Gothic2Notr(main+0x25c) [0xaaaac725dd5c]

Aborted (core dumped) 
```
