### ISSUE TITLE
 Cannot interact with NPC who is sleeping

### ISSUE THREAD

**Issue by polaskin** [Try/OpenGothic#560]
I'm having this issue, where I cannot interact with a sleeping NPC. Clicking on him does nothing. Spawning a monster does wake him up, as he will try to kill it, but immediately afterwards he goes back to sleep. In the meantime, I still cannot interact with him in any way.
Being stuck right now in the pirates camp, where I cannot talk with Morgan

Game is run in MacOS with M1 Pro if that helps in any way

**Comment by Try** [comment]
Hi, @polaskin and thanks for report!

Should be fixed now

**Comment by polaskin** [comment]
Thanks for the quick action. Unfortunately upon checking, I still cannot interact with them

**Comment by Try** [comment]
Could it be due to save-game state? Can you check, if bug still persist after sleep(of player)?

**Comment by polaskin** [comment]
oh yes, that worked. thanks
