### ISSUE TITLE
L’Hiver Mod: Sewer key discarded prematurely, leaving player locked out

### ISSUE THREAD

**Issue by AlexJakeGreen** [Try/OpenGothic#811]
When playing with the L’Hiver mod, there is a feature that automatically discards keys when they are "no longer needed." However, this logic can fail in certain cases and softlock the player:

1. A few in-game days ago, I unlocked the sewer door using Attila's key.
2. After opening the door, the game automatically discarded the key, as per L’Hiver mod's feature (I guess).
3. Now, the sewer door has closed again, but I no longer have the key, Attila says his job is done, and there is no way to re-enter the sewer.

Mod URL L'Hiver 1.3 https://drive.google.com/file/d/14ocKhiAvBkmujYghIzZJWLU93yxvHWT1/view

[save_slot_1.sav.gz](https://github.com/user-attachments/files/22933428/save_slot_1.sav.gz)

**Comment by Try** [comment]
Hi, @AlexJakeGreen and thanks for the report!

It seems, in the save-game that you provided key is already lost. Do you have earlier save, so disappearance of the key can be reproduced?

**Comment by AlexJakeGreen** [comment]
Keys are discarded for chests too. I will prepare a new save-game in a couple of days.

**Comment by AlexJakeGreen** [comment]
I am adding a save-game for a chest in Xardas tower -- it is easy to prepare because it is a start of the game: [save_slot_1.sav.gz](https://github.com/user-attachments/files/22963691/save_slot_1.sav.gz)
The chest was never opened in this save-game.
After the chest is opened, we can see a message saying something like „a chest key was thrown away“:
<img width="910" height="547" alt="Image" src="https://github.com/user-attachments/assets/e94c9978-9acf-4bc0-8588-a6b87b053298" />
 
Then loot everything and close the chest. Make an attempt to open the chest again, and a new message appears „I need a key or a pick“:
<img width="910" height="879" alt="Image" src="https://github.com/user-attachments/assets/e2036e52-42e3-4624-8cde-f65e900fb97e" />


Sewer door -- I am still working on preparing a save-game.

**Comment by AlexJakeGreen** [comment]
Sewer door with a rusted key: [save_slot_1.sav.gz](https://github.com/user-attachments/files/22968316/save_slot_1.sav.gz)

**Comment by AlexJakeGreen** [comment]
Another example -- a tower door in Khorinis. Once entered the tower, the Chosen One can't get out of there: [save_slot_1.sav.gz](https://github.com/user-attachments/files/22979439/save_slot_1.sav.gz)
Steps to reproduce:
1 Enter the tower
Observed: key discarded, door is closed, the Hero can't go outside.

**Comment by Try** [comment]
For Xardas tower, chest has a script attached to it:
```
func void REMKE_XAR01_S1() {
  if (SELF.ID == 0 && NPC_HASITEMS(HERO, ITKE_XARDAS) >= 1) {
    PRINT(PRINT_DELCHESTKEY);
    SND_PLAY("DOOR_UNLOCK_MOD");
    NPC_REMOVEINVITEMS(HERO, ITKE_XARDAS, 1);
  };
};
```
Looks like intended behavior, in regards to discarding the key.

for sewer key, it's essentially the same:
```
func void REMKE_CITYTHIEF01_S1() {
  if (SELF.ID == 0 && NPC_HASITEMS(HERO, ITKE_THIEFGUILDKEY_MIS) >= 1) {
    PRINT(PRINT_DELDOORKEY);
    SND_PLAY("DOOR_UNLOCK_MOD");
    NPC_REMOVEINVITEMS(HERO, ITKE_THIEFGUILDKEY_MIS, 1);
  };
};
```

Unless, based game does memorizes, if door/chest was ever unlocked - this look like intended behavior so far

**Comment by AlexJakeGreen** [comment]
It looks like the door does not remember that is already opened using a key. 
💡 Maybe, someone can check, how it works in original engine? The original game does not discard keys, but I guess it „remembers“ if the door/chest is already opened: 

1. open door or chest that require a key
2. remove the key from inventory
3. open door or chest again

If on step 3 we still can interact with door or chest -- then original game „remembers“ if the door is already opened.

**Comment by Try** [comment]
According to https://discord.com/channels/989316194148433950/989333514543587339/1429868085225062531

Game should memorize indeed, however would be nice to get confirmation by someone who can do testing locally (even with vanilla game)

**Comment by thokkat** [comment]
https://github.com/user-attachments/assets/8e487db0-ced4-40a8-9b59-85f72dc5b18e

Chests that can only be opened with a key  behave the same.

**Comment by Try** [comment]
Done!

Many thanks for confirming, @thokkat !

**Comment by Attilar576** [comment]
so may I ask why the problem is closed? For me, it still persists playing Lhiver, e.g. making the teleport to the harbor useless, since the door remains closed after the first opening.

**Comment by Try** [comment]
@Attilar576 

Closed as since [99a0c86](https://github.com/Try/OpenGothic/commit/99a0c866d95b584beecca9976d17dd8fe0464675) game will memorize what locks were unlocked. Unfortunately this wont help if you already have a save without the key and closed door - you would need to use marvin to get a new key once.

**Comment by Attilar576** [comment]
Ah I'm sorry, I made a mistake - it works :)
