### ISSUE TITLE
LHiver Mod: Enemies don't drop their shields

### ISSUE THREAD

**Issue by Attilar576** [Try/OpenGothic#819]
Killing enemies with shields, it's not possible to collect them after defeating them, e.g. with [this LHiver Version](https://forum.worldofplayers.de/forum/threads/1608407-RELEASE-Gothic-II-Originale-L-Hiver-Edition-Deutsche-Version)

[save_slot_17.sav.zip](https://github.com/user-attachments/files/23056155/save_slot_17.sav.zip)

**Comment by Try** [comment]
Should work now

**Comment by Attilar576** [comment]
> Should work now

Awesome, it works now upon defeating the enemy in a fight. Good job, thank you!!

Which still doesn't work is: Killing the enemy with one blow before he was able to get armed, I can only loot his melee weapon, but not his shield.

**Comment by Try** [comment]
Hi,
I don't have a save with easy to kill enemy to test, but [37acaed](https://github.com/Try/OpenGothic/commit/37acaede8bb8969a9c04f3274a7b7cfeaabb5df6) should work.

**Comment by Attilar576** [comment]
Yes, that works!! I tested it with Brago at the start. Thanks a lot!
